(function(root){'use strict';
const KEY='sentinel-v5';
function read(){const d=JSON.parse(localStorage.getItem(KEY)||'{"observations":[],"actions":[],"audit":[]}');if(!Array.isArray(d.observations)||!Array.isArray(d.actions)||!Array.isArray(d.audit))throw Error('Invalid saved workspace');return d;}
function write(d){localStorage.setItem(KEY,JSON.stringify(d));window.dispatchEvent(new Event('krishi-records'));}
function plan(d,o,now=Date.now()){const existing=d.actions.find(a=>a.status!=='Closed'&&d.observations.find(x=>x.id===a.observationId)?.fieldId===o.fieldId);if(existing)return existing;const a={id:'KR-'+crypto.randomUUID().slice(0,8),observationId:o.id,createdAt:now,due:now+86400000,status:'Open',review:'',checks:{}};d.actions.push(a);return a;}
function linkScan(d,fieldId,scan){const o=d.observations.filter(x=>x.fieldId===fieldId).sort((a,b)=>b.at-a.at)[0];if(!o)throw Error('Choose a saved field first.');o.scans=o.scans||[];const previous=o.scans.findIndex(x=>x.id===scan.id);if(previous>=0)o.scans[previous]=scan;else o.scans.push(scan);if(o.scans.length>6)o.scans.shift();d.audit.push({at:Date.now(),text:'Photo assessment linked to '+o.field});return o;}
function close(d,id,now=Date.now()){const a=d.actions.find(x=>x.id===id);if(!a)throw Error('Action plan not found.');const o=d.observations.find(x=>x.id===a.observationId);if(!d.observations.some(x=>x.fieldId===o.fieldId&&x.at>a.createdAt))throw Error('Record a fresh follow-up before closing.');a.status='Closed';a.closedAt=now;d.audit.push({at:now,text:'Action closed with follow-up evidence.'});return a;}
function validateBackup(d){if(!d||!Array.isArray(d.observations)||!Array.isArray(d.actions)||!Array.isArray(d.audit))throw Error('Invalid backup format.');if(d.observations.length>1000||d.actions.length>2000||d.audit.length>10000)throw Error('Backup is too large.');const ids=new Set();for(const o of d.observations){if(typeof o.id!=='string'||ids.has(o.id)||typeof o.fieldId!=='string'||!Number.isFinite(o.at)||typeof o.field!=='string'||typeof o.village!=='string'||typeof o.crop!=='string'||!Number.isInteger(o.sampled)||o.sampled<1||!Number.isInteger(o.affected)||o.affected<0||o.affected>o.sampled)throw Error('Invalid observation in backup.');ids.add(o.id);if(o.photo&&!/^data:image\/(jpeg|png|webp);base64,/.test(o.photo))throw Error('Invalid photo in backup.');if(o.scans&&(!Array.isArray(o.scans)||o.scans.some(s=>typeof s.id!=='string'||typeof s.disease!=='string'||typeof s.source!=='string'||!Number.isFinite(s.at))))throw Error('Invalid scan in backup.');}const acts=new Set();for(const a of d.actions){if(typeof a.id!=='string'||acts.has(a.id)||!ids.has(a.observationId)||!Number.isFinite(a.due)||!Number.isFinite(a.createdAt)||!['Open','Reviewed','Closed'].includes(a.status)||typeof a.review!=='string')throw Error('Invalid action in backup.');acts.add(a.id);}for(const a of d.audit)if(!Number.isFinite(a.at)||typeof a.text!=='string')throw Error('Invalid activity in backup.');return d;}
function merge(base,incoming){validateBackup(incoming);const d=JSON.parse(JSON.stringify(base));for(const k of ['observations','actions']){const ids=new Set(d[k].map(x=>x.id));d[k].push(...incoming[k].filter(x=>!ids.has(x.id)));}d.audit.push({at:Date.now(),text:'Backup merged; existing records retained.'});return d;}
function futureHours(h,currentTime){if(!h?.time?.length)return h;const index=h.time.findIndex(t=>t>=currentTime);if(index<0)return Object.fromEntries(Object.keys(h).map(k=>[k,[]]));return Object.fromEntries(Object.entries(h).map(([k,v])=>[k,Array.isArray(v)?v.slice(index):v]));}
const api={read,write,plan,linkScan,close,validateBackup,merge,futureHours};if(typeof module!=='undefined')module.exports=api;root.KrishiWorkflow=api;
})(typeof window==='undefined'?globalThis:window);
