const {test}=require('node:test'),assert=require('node:assert/strict');
const W=require('../workflow'),I=require('../i18n');
const o={id:'o1',fieldId:'f1',field:'North',village:'Nashik',crop:'Tomato',at:1000,sampled:20,affected:4,trap:null};
const fixture=()=>({observations:[{...o}],actions:[],audit:[]});
test('scan, action and repeat observation form one field workflow',()=>{const d=fixture();W.linkScan(d,'f1',{id:'scan1',at:2000,disease:'Uncertain',source:'Photo'});const a=W.plan(d,o,2000);assert.equal(W.plan(d,o,3000).id,a.id);assert.throws(()=>W.close(d,a.id,4000),/follow-up/);d.observations.push({...o,id:'o2',at:4000,affected:2});assert.equal(W.close(d,a.id,5000).status,'Closed');assert.equal(d.observations[0].scans.length,1)});
test('scan updates are idempotent and unknown field rejected',()=>{const d=fixture();for(let i=0;i<2;i++)W.linkScan(d,'f1',{id:'s',at:2000,disease:'Uncertain',source:'Photo'});assert.equal(d.observations[0].scans.length,1);assert.throws(()=>W.linkScan(d,'missing',{id:'s'}));});
test('restore retains originals and rejects invalid records',()=>{const d=fixture(),incoming=fixture();incoming.observations[0].affected=1;const merged=W.merge(d,incoming);assert.equal(merged.observations[0].affected,4);incoming.observations[0].photo='invalid';assert.throws(()=>W.validateBackup(incoming));});
test('forecast excludes past hours',()=>{const h={time:['2026-09-10T00:00','2026-09-10T10:00','2026-09-10T11:00'],temperature_2m:[20,25,27]};assert.deepEqual(W.futureHours(h,'2026-09-10T09:15').temperature_2m,[25,27]);assert.equal(W.futureHours(h,'2026-09-11T00:00').time.length,0);});
test('interface catalog covers three selectable languages',()=>{assert.deepEqual(I.languages,['en','hi','mr']);assert.ok(Object.keys(I.entries).length>400);for(const [key,row]of Object.entries(I.entries))for(const language of ['hi','mr'])assert.ok(row[language],`${language}: ${key}`);for(const lang of ['hi','mr'])assert.notEqual(I.t('Record observation',lang),'Record observation');assert.equal(I.t('Record observation','en'),'Record observation');});
